 #################### 本地开发环境配置 ####################
server:
  servlet:
    context-path: /core-example
  port: 8088

#################### DataSource Configuration ##########################
#spring 在引入jdbc后，就默认开启了数据库连接池，所以可以不配置
spring:
  datasource: #数据源配置
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.44.89:1521:orcl
    username: lyrlzywcms
    password: lyrlzywcms
    tomcat:
      max-idle: 10 #最大的空闲连接数量
      max-wait: 10000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      min-idle: 3 # 必须保持连接的最小数
      initial-size: 3 #启动连接池时，初始建立的连接数量
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000 # 1分钟检查一次：空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

###################### jl esscard esb config ##########################
jl-esscard:
  esb-url: http://192.168.122.172:8080/YlzinfoESB/esbproxy
  esb-user: web
  esb-password: 3B5C37D96F9A0987FC260A1B13F57701
  esb-log-level: debug

####################### fj ggfwwt esb config ##########################
fj-ggfwwt:
  esb-url: http://220.160.52.229:9010/esb/esbproxy
  esb-user: fjweb
  esb-password: 3B5C37D96F9A0987FC260A1B13F57701
  esb-log-level: debug

####################### smrlzyw esb config ##########################
smrlzyw:
  esb-url: http://220.162.229.82:5501/esb/esbproxy
  esb-user: smzpapp
  esb-password: 908723B50EE7C0966AE5488C5BF978D7
  esb-log-level: debug

####################### smmsh5 esb config ##########################
smmsh5:
  esb-url: http://220.162.229.82:5501/esb/esbproxy
  esb-user: smmsh5
  esb-password: 2A47C27C34B4E838
  esb-log-level: debug