
package com.hh.core.business.smrlzyw.company.webservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InterfaceserviceService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://202.109.226.172:8182/Convergence/webservice/interfaceservice?wsdl")
public class InterfaceserviceService
    extends Service
{

    private final static URL INTERFACESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INTERFACESERVICESERVICE_EXCEPTION;
    private final static QName INTERFACESERVICESERVICE_QNAME = new QName("http://tempuri.org/", "InterfaceserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://202.109.226.172:8182/Convergence/webservice/interfaceservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERFACESERVICESERVICE_WSDL_LOCATION = url;
        INTERFACESERVICESERVICE_EXCEPTION = e;
    }

    public InterfaceserviceService() {
        super(__getWsdlLocation(), INTERFACESERVICESERVICE_QNAME);
    }

    public InterfaceserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERFACESERVICESERVICE_QNAME, features);
    }

    public InterfaceserviceService(URL wsdlLocation) {
        super(wsdlLocation, INTERFACESERVICESERVICE_QNAME);
    }

    public InterfaceserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERFACESERVICESERVICE_QNAME, features);
    }

    public InterfaceserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Interfaceservice
     */
    @WebEndpoint(name = "InterfaceservicePort")
    public Interfaceservice getInterfaceservicePort() {
        return super.getPort(new QName("http://tempuri.org/", "InterfaceservicePort"), Interfaceservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Interfaceservice
     */
    @WebEndpoint(name = "InterfaceservicePort")
    public Interfaceservice getInterfaceservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "InterfaceservicePort"), Interfaceservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERFACESERVICESERVICE_EXCEPTION!= null) {
            throw INTERFACESERVICESERVICE_EXCEPTION;
        }
        return INTERFACESERVICESERVICE_WSDL_LOCATION;
    }

}
