
package com.hh.core.business.smrlzyw.company.webservice.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Interfaceservice", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Interfaceservice {


    /**
     * 
     * @param queryjson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "query_single_new")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query_single_new", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QuerySingleNew")
    @ResponseWrapper(localName = "query_single_newResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QuerySingleNewResponse")
    public String querySingleNew(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryjson", targetNamespace = "")
        String queryjson);

    /**
     * 
     * @param queryjson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "query_multi_new")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query_multi_new", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QueryMultiNew")
    @ResponseWrapper(localName = "query_multi_newResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QueryMultiNewResponse")
    public String queryMultiNew(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryjson", targetNamespace = "")
        String queryjson);

    /**
     * 
     * @param queryjson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "verify_multi_new")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify_multi_new", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifyMultiNew")
    @ResponseWrapper(localName = "verify_multi_newResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifyMultiNewResponse")
    public String verifyMultiNew(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryjson", targetNamespace = "")
        String queryjson);

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "thirdParty", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ThirdParty")
    @ResponseWrapper(localName = "thirdPartyResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ThirdPartyResponse")
    public String thirdParty(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml);

    /**
     * 
     * @param password
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorization", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.AuthorizationResponse")
    public String authorization(
        @WebParam(name = "userid", targetNamespace = "")
        String userid,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "boutique_query_multi")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "boutique_query_multi", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.BoutiqueQueryMulti")
    @ResponseWrapper(localName = "boutique_query_multiResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.BoutiqueQueryMultiResponse")
    public String boutiqueQueryMulti(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "electronic_doNoApplyAndNoLogExcute")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "electronic_doNoApplyAndNoLogExcute", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ElectronicDoNoApplyAndNoLogExcute")
    @ResponseWrapper(localName = "electronic_doNoApplyAndNoLogExcuteResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ElectronicDoNoApplyAndNoLogExcuteResponse")
    public String electronicDoNoApplyAndNoLogExcute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param queryjson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "electronic_query_multi")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "electronic_query_multi", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ElectronicQueryMulti")
    @ResponseWrapper(localName = "electronic_query_multiResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ElectronicQueryMultiResponse")
    public String electronicQueryMulti(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryjson", targetNamespace = "")
        String queryjson);

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     * @throws JSONException_Exception
     */
    @WebMethod(operationName = "verify_single")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify_single", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifySingle")
    @ResponseWrapper(localName = "verify_singleResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifySingleResponse")
    public String verifySingle(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml)
        throws JSONException_Exception
    ;

    /**
     * 
     * @param queryJson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "excitation_query")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "excitation_query", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ExcitationQuery")
    @ResponseWrapper(localName = "excitation_queryResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.ExcitationQueryResponse")
    public String excitationQuery(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryJson", targetNamespace = "")
        String queryJson);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIP", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.GetIP")
    @ResponseWrapper(localName = "getIPResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.GetIPResponse")
    public String getIP();

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "query_single")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query_single", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QuerySingle")
    @ResponseWrapper(localName = "query_singleResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QuerySingleResponse")
    public String querySingle(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml);

    /**
     * 
     * @param queryjson
     * @param guid
     * @param interfaceid
     * @return
     *     returns java.lang.String
     * @throws JSONException_Exception
     */
    @WebMethod(operationName = "verify_single_new")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify_single_new", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifySingleNew")
    @ResponseWrapper(localName = "verify_single_newResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifySingleNewResponse")
    public String verifySingleNew(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryjson", targetNamespace = "")
        String queryjson)
        throws JSONException_Exception
    ;

    /**
     * 
     * @param queryJson
     * @param guid
     * @param applyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "microServerGxjkQuery", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.MicroServerGxjkQuery")
    @ResponseWrapper(localName = "microServerGxjkQueryResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.MicroServerGxjkQueryResponse")
    public String microServerGxjkQuery(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "applyCode", targetNamespace = "")
        String applyCode,
        @WebParam(name = "queryJson", targetNamespace = "")
        String queryJson);

    /**
     * 
     * @param queryJson
     * @param guid
     * @param applyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "microServerFwjkQuery", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.MicroServerFwjkQuery")
    @ResponseWrapper(localName = "microServerFwjkQueryResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.MicroServerFwjkQueryResponse")
    public String microServerFwjkQuery(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "applyCode", targetNamespace = "")
        String applyCode,
        @WebParam(name = "queryJson", targetNamespace = "")
        String queryJson);

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "query_multi")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query_multi", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QueryMulti")
    @ResponseWrapper(localName = "query_multiResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.QueryMultiResponse")
    public String queryMulti(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml);

    /**
     * 
     * @param guid
     * @param queryxml
     * @param interfaceid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "verify_multi")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify_multi", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifyMulti")
    @ResponseWrapper(localName = "verify_multiResponse", targetNamespace = "http://tempuri.org/", className = "com.hh.core.business.smrlzyw.company.webservice.wsdl.VerifyMultiResponse")
    public String verifyMulti(
        @WebParam(name = "guid", targetNamespace = "")
        String guid,
        @WebParam(name = "interfaceid", targetNamespace = "")
        String interfaceid,
        @WebParam(name = "queryxml", targetNamespace = "")
        String queryxml);

}
