
package com.hh.core.business.smrlzyw.company.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JSONException", targetNamespace = "http://tempuri.org/")
public class JSONException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JSONException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public JSONException_Exception(String message, JSONException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public JSONException_Exception(String message, JSONException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.hh.core.business.smrlzyw.company.webservice.wsdl.JSONException
     */
    public JSONException getFaultInfo() {
        return faultInfo;
    }

}
